use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :jbb, JBBWeb.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}],
  url: [host: {:system, "HOST"}, port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
  root: "."

# Do not print debug messages in production
config :logger, level: :info

config :jbb, JBB.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: Map.fetch!(System.get_env(), "DB_HOSTNAME"),
  username: Map.fetch!(System.get_env(), "DB_USERNAME"),
  password: Map.fetch!(System.get_env(), "DB_PASSWORD"),
  database: Map.fetch!(System.get_env(), "DB_NAME"),
  pool_size: Map.fetch!(System.get_env(), "POOL_SIZE"),
